aviation_ranks = {
    "AD1":"Aviation Machinist's Mate Petty Officer 1st Class",
    "H":"***UNKNOWN***",
    "ZZ":"***UNKNOWN***",
    "ABF":"Aviation Boatswain's Mate (Launching & Recovery) Petty Officer",
    "1520":"***UNKNOWN***",
    "AMEAN":"Aviation Structural Mechanic (Safety Equipment) Airman",
    "8342":"***UNKNOWN***",
    "AO2":"Aviation Ordnanceman Petty Officer 2nd Class",
    "AE1":"Aviation Electrician's Mate Petty Officer 1st Class",
    "ADAN":"Aviation Machinist's Mate Airman",
    "na2":"Naval Airman Second Class",
    "7022":"***UNKNOWN***",
    "unk":"***UNKNOWN***",
    "E5":"Petty Officer Second Class",
    "QMSA":"Quartermaster Seaman Apprentice",
    "AME3":"Aviation Structural Mechanic (Safety Equipment) Petty Officer 3rd Class",
    "ATAN":"Aviation Electronics Technician Airman",
    "AT3":"Aviation Electronics Technician Petty Officer 3rd Class",
    "AME2":"Aviation Structural Mechanic (Safety Equipment) Petty Officer 2nd Class",
    "UNDES":"***UNKNOWN***",
    "PO3":"Petty Officer 3rd Class",
    "AO1":"Aviation Ordnanceman Petty Officer 1st Class",
    "99":"***UNKNOWN***",
    "ASAN":"Aviation Support Equipment Technician Striker",
    "ABEAN":"Aviation Boatswain's Mate (Launching & Recovery) Airman",
    "MMFN":"Machnist's Mate Fireman",
    "AWSC":"Helicopter Warfare Specialist Chief Petty Officer",
    "5":"***UNKNOWN***",
    "6":"***UNKNOWN***",
    "ADC":"Aviation Machinist's Mate Chief Petty Officer",
    "0000":"***UNKNOWN***",
    "AWS2":"Helicopter Warfare Specialist",
    "AMC":"Aviation Structural Mechanic Chief Petty Officer",
    "0001":"***UNKNOWN***",
    "E-3":"Seaman",
    "8839":"***UNKNOWN***",
    "8215":"***UNKNOWN***",
    "ADAA":"Aviation Machinist's Mate Airman Apprentice",
    "AWR2":"***UNKNOWN***",
    "am":"***UNKNOWN***",
    "AEC":"Aviation Electrician's Mate Chief Petty Officer",
    "AWR":"Naval Aircrewman",
    "AWRC":"***UNKNOWN***",
    "0":"***UNKNOWN***",
    "PR":"***UNKNOWN***",
    "UR":"***UNKNOWN***",
    "1":"***UNKNOWN***",
    ".":"***UNKNOWN***",
    "e5":"Petty Officer 2nd Class",
    "AT1":"Aviation Electronics Technician Petty Officer 1st Class",
    "NAC":"***UNKNOWN***",
    "AM2":"Aviation Metalsmith Petty Officer 2nd Class",
    "AWF":"Naval Aircrew Mechanical",
    "ABE":"Aviation Boatswain's Mate (Launching & Recovery) Petty Officer 1st Class",
    "AA":"Airman Apprentice",
    "ABH1":"Aviation Boatswain's Mate Aircraft Handler Petty Officer 1st Class",
    "AME":"Aviation Structural Mechanic (Safety Equipment) Petty Officer 1st Class",
    "ABH2":"Aviation Boatswain's Mate Aircraft Handler Petty Officer 2nd Class",
    "UNK":"***UNKNOWN***",
    "AS":"Apprentice Seaman",
    "AMAN":"Aviation Structural Mechanic Airman",
    "AMAA":"Aviation Structural Mechanic Airman Apprentice",
    "AMAR":"Aviation Structural Mechanic Airman Recruit",
    "AE3":"Aviation Electrician's Mate Petty Officer 3rd Class",
    "ABH":"Aviation Boatswain's Mate Aircraft Handler Petty Officer",
    "TM3":"Torpedoman's Mate Petty Officer 3rd Class",
    "HMC":"Hospital Corpsman Chief Petty Officer",
    "RM2":"Radioman Petty Officer 2nd Class",
    "AW1":"Aviation Anti-Submarine Warfare Operator Petty Officer 1st Class",
    "AW2":"Aviation Anti-Submarine Warfare Operator Petty Officer 2nd Class",
    "A03":"Aviation Ordnanceman Petty Officer 3rd Class",
    "AM":"Armorer's Mate",
    "AD":"Aviation Machnist's Mate Petty Officer 1st Class",
    "AT2":"Aviation Electronics Technician Petty Officer 2nd Class",
    "AB":"Aviation Boatswain's Mate Petty Officer",
    "AW3":"Aviation Anti-Submarine Warfare Operator Petty Officer 3rd Class",
    "AME1":"Aviation Structural Mechanic (Safety Equipment) Petty Officer 1st Class",
    "AD3":"Aviation Machinist's Mate Petty Officer 3rd Class",
    "AO":"Aviation Ordnanceman Petty Officer",
    "AT":"Aviation Electronics Technician Petty Officer",
    "AE":"Aviation Electrician's Mate Petty Officer 1st Class",
    "ABSN":"***UNKNOWN***",
    "3":"***UNKNOWN***",
    "ABHC":"Aviation Boatswain's Mate Aircraft Handler Chief Petty Officer",
    "AOC":"Aviation Ordnanceman Chief Petty Officer",
    "ATC":"Aviation Electronics Technician Chief Petty Officer",
    "AM1":"Aviation Structural Mechanic Petty Officer 1st Class",
    "AM3":"Aviation Structural Mechanic Petty Officer 3rd Class",
    "ABHAA":"Aviation Boatswain's Mate Aircraft Handler Airman Apprentice",
    "AOAN":"Aviation Ordnanceman Airman",
    "AD2":"Aviation Machinist's Mate Petty Officer 2nd Class",
    "AEAN":"Aviation Electrician's Mate Airman",
    "AN":"Airman",
    "2":"***UNKNOWN***",
    "AR":"Airman Recruit",
    "ABHAN":"Aviation Boatswain's Mate Aircraft Handler Airman",
    "ABH3":"Aviation Boatswain's Mate Aircraft Handler Petty Officer 3rd Class",
    "AWS3":"Naval Aircrewman Petty Officer 3rd Class",
    "AWS":"Naval Aircrewman",
    "AE2":"Aviation Electrician's Mate Petty Officer 2nd Class",
    "HM2":"Hospital Corpsman Petty Officer 2nd Class",
    "AECS":"Aviation Electrician's Mate Senior Chief Petty Officer",
    "ABHAR":"Aviation Boatswain's Mate Aircraft Handler Airman Recruit",
    "AW":"Aviation Anti-Submarine Warfare Operator Petty Officer 1st Class",
}

non_aviation_ranks = {
    "AMAN":"Aviation Structural Mechanic Airman",
    "AK2":"Aviation Storekeeper Petty Officer 2nd Class",
    "FC3":"Fire Controlman Petty Officer 3rd Class",
    "HM2":"Hospital Corpsman Petty Officer Second Class",
    "LSSN":"***UNKNOWN***",
    "ABHSN":"***UNKNOWN***",
    "ABECS":"***UNKNOWN***",
    "PR2":"Parachute Rigger Petty Officer 2nd Class",
    "EM1":"Electrician's Mate Petty Officer 1st Class",
    "RPC":"Religious Program Specialist Chief Petty Officer",
    "QMSA":"Quartermaster Seaman Apprentice",
    "ETSN":"Electronics Technician Seaman",
    "HTC":"Hull Maintenance Technician Chief Petty Officer",
    "GM2":"Gunner's Mate 2nd Class Petty Officer",
    "HT1":"Hull Maintenance Technician Petty Officer 1st Class",
    "HA":"Hospital Apprentice",
    "AOCM":"Aviation Ordnanceman Master Chief Petty Officer",
    "CTM3":"Cryptologic (Maintenance Branch) Petty Officer 3rd Class",
    "GMSR":"Gunner's Mate Seaman Recruit",
    "LNC":"Legalman Chief Petty Officer",
    "AOC":"Aviation Ordnanceman Chief Petty Officer",
    "FCC":"Fire Control Technician Chief Petty Officer",
    "BMC":"Boatswain's Mate Chief Petty Officer",
    "IS3":"Intelligence Specialist Petty Officer 2nd Class",
    "DCCS":"Damage Controlman Senior Chief Petty Officer",
    "HTFR":"Hull Maintenance Technician Fireman Recruit",
    "ADCS":"Aviation Machinist's Mate Senior Chief Petty Officer",
    "ABFSA":"***UNKNOWN***",
    "SHCS":"Ship's Serviceman Senior Chief Petty Officer",
    "MCCS":"Mass Communications Specialist",
    "MMCS":"Machnist's Mate Senior Chief Petty Officer",
    "ABHSA":"***UNKNOWN***",
    "ABFSN":"***UNKNOWN***",
    "PSSN":"Personnel Specialist Seaman",
    "ADC":"Aviation Machinist's Mate Chief Petty Officer",
    "PS2":"Petty Officer 2nd Class",
    "MA2":"Machine Accountant Petty Officer 2nd Class",
    "CS1":"Commissaryman Petty Officer 1st Class",
    "AA":"Airman Apprentice",
    "ISSN":"Intelligence Specialist Seaman",
    "MR3":"Machinery Repairman Petty Officer 3rd Class",
    "ITSR":"Information Technician Seaman Recruit",
    "EN2":"Engineman Petty Officer 2nd Class",
    "ASAA":"***UNKNOWN***",
    "GM3":"Gunner's Mate 3rd Class Petty Officer",
    "ETC":"Electronic's Technician Chief Petty Officer",
    "YN2":"Yeoman Petty Officer 2nd Class",
    "YNSR":"Yeoman Seaman Recruit",
    "JO3":"Journalist Petty Officer 3rd Class",
    "CTR":"Cryptologic Technician (Collection)",
    "DK3":"Disbursing Clerk Petty Officer 3rd Class",
    "ACAN":"Air Control Man Airman",
    "MMFR":"Machnist's Mate Fireman Recruit",
    "SKC":"Storekeeper Chief Petty Officer",
    "QMSN":"Quartermaster Seaman",
    "ENFA":"Engine Man Fireman Apprentice",
    "ABHC":"Aviation Boatswain's Mate Aircraft Handler Chief Petty Officer",
    "ADAR":"Aviation Machnist's Mate Airman Recruit",
    "PNSN":"Personnelman Seaman",
    "PC1":"Postal Clerk Petty Officer 1st Class",
    "AMEAA":"Aviation Structural Mechanic (Safety Equipment) Airman Apprentice",
    "AW2":"Aviation Anti-Submarine Warfare Operator Petty Officer 2nd Class",
    "AZ1":"Aviation Maintenance Administrationman Petty Officer 1st Class",
    "YN3":"Yeoman Petty Officer 3rd Class",
    "AO1":"Aviation Ordnanceman Petty Officer 1st Class",
    "PS1":"Petty Officer First Class",
    "ENFN":"Engine Man Fireman Recruit",
    "ASAR":"Apprentice Seaman (Aviation Rigger)",
    "AEAA":"Aviation Electrician's Mate Airman Apprentice",
    "AG1":"Aerographer's Mate Petty Officer 1st Class",
    "DCC":"Damage Controlman Chief Petty Officer",
    "SKSA":"Storekeeper Seaman Apprentice",
    "EMC":"Electrician's Mate Chief Petty Officer",
    "TM2":"Torpedoman's Mate Petty Officer 2nd Class",
    "QMCS":"Quartermaster Senior Chief Petty Officer",
    "MC3":"Mass Communications Specialist",
    "AR":"Airman Recruit",
    "BM":"Boatswain's Mate",
    "IC":"Interior Communications Electrician Petty Officer",
    "GM":"Gunner's Mate",
    "EM":"Electrician's Mate Petty Officer",
    "SR":"Seaman Recruit",
    "FC":"Fire Controlman",
    "ABH":"Aviation Boatswain's Mate Aircraft Handler Petty Officer",
    "EN":"Engineman",
    "MM":"Machinist's Mate",
    "QM":"Quartermaster",
    "LS":"Logistic's Specialist",
    "YN":"Yeoman Petty Officer 1st Class",
    "AOCS":"Aviation Ordnanceman Senior Chief Petty Officer 1st Class",
    "SA":"Seaman Apprentice",
    "AT":"***UNKNOWN***",
    "DC":"Damage Controlman",
    "AM":"Armorer's Mate",
    "EO3":"Equipment Operator Petty Officer 3rd Class",
    "SH":"Ship's Serviceman",
    "AF":"***UNKNOWN***",
    "ABF2":"Aviation Boatswain's Mate (Fuel Handler) Petty Officer 2nd Class",
    "AB":"Able Seaman",
    "AG":"Aerographer's Mate",
    "AMAR":"Aviation Structural Mechanic Airman Recruit",
    "AT3":"Aviation Electronics Technician Petty Officer 3rd Class",
    "MR":"Machinery Repairman",
    "AC":"Air Traffic Controller",
    "CTT":"Communications Technician (Technical Branch) Petty Officer 1st Class",
    "AE":"Aviation Electrician's Mate",
    "PS":"Personnel Specialist",
    "FR":"Fireman Recruit",
    "FN":"Fireman",
    "PR":"Aircrew Survival Equipmentman",
    "OS":"Ordinary Seaman",
    "HM":"Hospital Corpsman",
    "MC2":"Mass Communications Specialist Petty Officer 2nd Class",
    "IT":"***UNKNOWN***",
    "SN":"Seaman",
    "LS2":"Logistics Specialist Petty Officer 2nd Class",
    "LS3":"Logistics Specialist Petty Officer 3rd Class",
    "MA3":"Machine Accountant Petty Officer 3rd Class",
    "LSSR":"***UNKNOWN***",
    "SHSR":"Ship's Serviceman Seaman Recruit",
    "AK1":"Aviation Storekeeper Petty Officer 1st Class",
    "AW1":"Aviation Anti-Submarine Warfare Operator Petty Officer 1st Class",
    "PSCM":"Master Chief Personnel Specialist",
    "OS1":"Operations Specialist Petty Officer 1st Class",
    "ABHCS":"***UNKNOWN***",
    "ABHSR":"***UNKNOWN***",
    "DC2":"Damage Controlman Petty Officer 2nd Class",
    "NC1":"Naval Counselor Petty Officer 1st Class",
    "ATAA":"Aviation Electronics Technician Airman Apprentice",
    "ABFSR":"***UNKNOWN***",
    "ITCM":"Information Technician Master Chief Petty Officer",
    "AME":"Aviation Structural Mechanic (Safety Equipment)",
    "CTT3":"Communications Technician (Technical Branch) Petty Officer 3rd Class",
    "FCSN":"Fire Control Technician Seaman",
    "CS":"Culinary Specialist",
    "AZ":"Aviation Maintenance Administrationman Petty Officer 1st Class",
    "ABE":"Aviation Boatswain's Equipment Mate",
    "HT":"Hull Maintenance Technician",
    "AO":"Aviation Ordnanceman",
    "AD":"Aviation Machinist Mate",
    "CSCM":"Commisaryman Master Chief Petty Officer",
    "AS":"Apprentice Seaman",
    "ABF":"Aviation Boatswain's Mate (Fuel Handler) Petty Officer First Class",
    "ASC":"Aviation Support Equipment Technician's Chief Petty Officer",
    "DCFR":"Damage Controlman Fireman Recruit",
    "PR1":"Parachute Rigger Petty Officer 1st Class",
    "PS3":"Personnel Specialist Petty Officer 3rd Class",
    "ETCS":"Electronics Technician Senior Chief Petty Officer",
    "EACN":"Engineering Aid Constructionman",
    "STG1":"Sonar Technician (Surface) Petty Officer 1st Class",
    "TM1":"Torpedoman's Mate Petty Officer 1st Class",
    "ATC":"Aviation Electronics Technician Chief Petty Officer",
    "AN":"Airman",
    "AGAR":"Aerographer's Mate Airman Recruit",
    "AME2":"Aviation Structural Mechanic (Safety Equipment) Petty Officer 2nd Class",
    "AZ2":"Aviation Maintenance Administrationman Petty Officer 2nd Class",
    "AD3":"Aviation Machnist's Mate Petty Officer 3rd Class",
    "AMEAN":"Aviation Structural Mechanic (Safety Equipment) Airman",
    "AME3":"Aviation Structural Mechanic (Safety Equipment) Petty Officer 3rd Class",
    "AD1":"Aviation Machnist's Mate Petty Officer 1st Class",
    "ASAN":"Aviation Support Equipment Technician Striker",
    "ET3":"Electronics Technician Petty Officer 3rd Class",
    "HM1":"Hospital Corpsman Petty Officer 1st Class",
    "AT2":"Aviation Electronics Technician Petty Officer 2nd Class",
    "CS3":"Commissaryman Petty Officer 3rd Class",
    "SKSN":"Storekeeper Seaman",
    "MR2":"Machinery Repairman Petty Officer 2nd Class",
    "MR1":"Machinery Repairman Petty Officer 1st Class",
    "DCFN":"Damage Controlman Fireman",
    "SK2":"Storekeeper 2nd Class Petty Officer",
    "AMC":"Aviation Structural Mechanic Chief Petty Officer",
    "AM3":"Aviation Structural Mechanic Petty Officer 3rd Class",
    "IT1":"Information Technician Petty Officer 1st Class",
    "DT2":"Dental Technician Petty Officer 2nd Class",
    "ET1":"Electronics Technician Petty Officer 1st Class",
    "BMSN":"Boatswain's Mate Seaman",
    "CTR2":"Cryptologic (Collection) Petty Officer 2nd Class",
    "AE2":"Aviation Electrician's Mate Petty Officer 2nd Class",
    "DC3":"Damage Controlman Petty Officer 3rd Class",
    "GMSN":"Gunner's Mate Seaman",
    "ABE1":"Aviation Boatswain's Mate (Launching & Recovery) Petty Officer 1st Class",
    "DCFA":"Damage Controlman Fireman Apprentice",
    "IC3":"Interior Communications Electrician Petty Officer 3rd Class",
    "SK3":"Storekeeper 3rd Class Petty Officer",
    "BM1":"Boatswain's Mate Petty Officer 1st Class",
    "CSSA":"Commissaryman Seaman Apprentice",
    "MMFN":"Machnist's Mate Fireman",
    "ABE3":"Aviation Boatswain's Mate (Launching & Recovery) Petty Officer 3rd Class",
    "AOAN":"Aviation Ordnanceman Airman",
    "AM2":"Aviation Metalsmith Petty Officer 2nd Class",
    "ICFN":"Interior Communications Electrician Fireman",
    "IS1":"Intelligence Specialist Petty Officer 1st Class",
    "ABH3":"Aviation Boatswain's Mate Aircraft Handler Petty Officer 3rd Class",
    "ABAN":"Aviation Boatswain's Mate Airman",
    "GMG":"Gunner's Mate (Guns) Petty Officer 1st Class",
    "CT":"Chief Telegrapher",
    "STG":"Sonar Technician (Surface) Petty Officer",
    "MA":"Master-At-Arms",
    "EA":"Engineering Aide",
    "MC":"Mass Communication Specialist",
    "IS":"***UNKNOWN***",
    "CTM":"Torpedoman's Mate Chief Petty Officer (WWII)",
    "MM3":"Machinist's Mate Petty Officer 3rd Class",
    "BM3":"Boatswain's Mate Petty Officer 3rd Class",
    "SK":"Storekeeper",
    "GSE":"Gas Turbine System Technician (Electrical) Petty Officer",
    "FA":"Fireman Apprentice",
    "LN":"Legalman",
    "DN":"Dentalman",
    "FT":"Fire Control Technician",
    "AV":"Avionics Technician",
    "ET":"Electronics Technician",
    "AZAN":"Aviation Maintenance Administrationman Airman",
    "nan":"***UNKNOWN***",
    "AD2":"Aviation Machinist's Mate Petty Officer 2nd Class",
    "AG3":"Aerographer's Mate Petty Officer 3rd Class",
    "SHSN":"Ship's Serviceman Seaman",
    "MM1":"Machinist's Mate 1st Class Petty Officer",
    "AM1":"Aviation Structural Mechanic Petty Officer 1st Class",
    "AO3":"Aviation Ordnanceman Petty Officer 3rd Class",
    "ABH1":"Aviation Boatswain's Mate Aircraft Handler Petty Officer 1st Class",
    "IS2":"Intelligence Specialist Petty Officer 2nd Class",
    "ATAN":"Aviation Electronics Technician Airman",
    "AS3":"Aviation Support Equipment Technician Petty Offcer 3rd Class",
    "EM3":"Electrician's Mate Petty Officer 3rd Class",
    "AS1":"Aviation Support Equipment Technician Petty Officer 1st Class",
    "AEAN":"Aviation Electrician's Mate Airman",
    "CSSN":"Commissaryman Seaman",
    "ABE2":"Aviation Boatswain's Mate (Launching & Recovery) Petty Officer 2nd Class",
    "ABAA":"Aviation Boatswain's Mate Airman Apprentice",
    "AE3":"Aviation Electrician's Mate Petty Officer 3rd Class",
    "MM2":"Machinist's Mate 2nd Class Petty Officer",
    "PR3":"Aircrew Survival Equipmentman Petty Officer 3rd Class",
    "PHAN":"Photographer's Mate Airman", 
    "PRAN":"Aircrew Survival Equipmentman Airman",
    "ABAR":"Aviation Boatswain's Mate Airman Recruit",
    "ITSN":"Information Technician Seaman",
    "MMFA":"Machinist's Mate Fireman Apprentice",
    "SH3":"Ship's Serviceman Petty Officer 3rd Class",
    "AMEAR":"Aviation Structural Mechanic (Safety Equipment) Airman Recruit",
    "IC1":"Interior COmmunications Electrician Petty Officer 1st Class",
    "SKSR":"Storekeeper Seaman Recruit",
    "CTT2":"Cryptologic (Technical Branch) Petty Officer 2nd Class",
    "BMSA":"Boatswain's Mate Seaman Apprentice",
    "EM2":"Electrician's Mate Petty Officer 2nd Class",
    "SH2":"Ship's Serviceman Petty Officer 2nd Class",
    "EN3":"Engineman Petty Officer 3rd Class",
    "AT1":"Aviation Electronics Technician Petty Officer 1st Class",
    "ABF1":"Aviation Boatswain's Mate (Fuel Handler) Petty Officer First Class",
    "AZAA":"Aviation Maintenance Administrationman Airman Apprentice",
    "SHSA":"Ship's Serviceman Seaman Apprentice",
    "PN2":"Personnelman Petty Officer 2nd Class",
    "FC2":"Fire Controlman Petty Officer 2nd Class",
    "OSSA":"Operations Specialist Seaman Apprentice",
    "EMFA":"Electrician's Mate Fireman Apprentice",
    "MA1":"Master-At-Arms Petty Officer 1st Class",
    "AMEC":"Aviation Structural Mechanic (Safety Equipment) Chief Petty Officer",
    "PCSN":"Postal Clerk Seaman",
    "ADAA":"Aviation Machinist's Mate Airman Apprentice",
    "TM3":"Torpedoman's Mate Petty Officer 3rd Class",
    "AC1":"Air Controlman Petty Officer 1st Class",
    "CSSR":"Commissaryman Seaman Recruit",
    "AB1":"Aviation Boatswain's Mate Petty Officer 1st Class",
    "IT2":"Information Technician Petty Officer 2nd Class",
    "ICC":"Interior Communications Electrician Chief Petty Officer",
    "BM2":"Boatswain's Mate Petty Officer 2nd Class",
    "EMFN":"Electrician's Mate Fireman",
    "YNSN":"Yeoman Seaman",
    "QM3":"Quartermaster 3rd Class Petty Officer",
    "IC2":"Interior Communications Electrician Petty Officer 2nd Class",
    "AZ3":"Aviation Maintenance Administrationman Petty Officer 3rd Class",
    "ET2":"Electronics Technician Petty Officer 2nd Class",
    "OS3":"Officer's Steward 3rd Class (Non Petty Officer)",
    "AMCS":"Aviation Structural Mechanic Senior Chief Petty Officer",
    "AS2":"Aviation Support Equipment Technician Petty Officer 2nd Class",
    "OSSN":"Operations Specialist Seaman",
    "HTFA":"Hull Maintenance Technician",
    "AO2":"Aviation Ordnanceman Petty Officer 2nd Class",
    "CS2":"Commissaryman Petty Officer 2nd Class",
    "AC2":"Air Controlman Petty Officer 2nd Class",
    "ABH2":"Aviation Boatswain's Mate Aircraft Handler Petty Officer 2nd Class",
    "ABF3":"Aviation Boatswain's Mate (Fuel Handler) Petty Officer 3rd Class",
    "EN1":"Engineman Petty Officer 1st Class",
    "HM3":"Hospital Corpsman Petty Officer 3rd Class",
    "AWAN":"Aviation Anti-Submarine Warfare Operator Airman",
    "AEAR":"Aviation Electrician's Mate Airman Recruit",
    "SK1":"Storekeeper 1st Class Petty Officer",
    "CTTSN":"Communications Technician (Technical Branch) Seaman",
    "ICFA":"Interior Communications Electrician Fireman Apprentice",
    "OS2":"Ordinary Seaman First Class",
    "MMC":"Machnist's Mate Chief Petty Officer",
    "PN3":"Personnelman Petty Officer 3rd Class",
    "GMC":"Gunner's Mate Chief Petty Officer",
    "HTFN":"Hull Maintenance Technician",
    "IT3":"Information Technician Petty Offier 3rd Class",
    "ABFC":"Aviation Boatswain's Mate (Fuel Handler) Chief Petty Officer",
    "LISR":"Lithographer Seaman Recruit",
    "LISN":"Lithographer Seaman",
    "ADAN":"Aviation Machinist's Mate Airman",
    "AOAR":"Aviation Ordnanceman Chief Petty Officer",
    "DC1":"Damage Controlman Petty Officer 1st Class",
    "ABEC":"Aviation Boatswain's Mate (Launching & Recovery) Chief Petty Officer",
    "AOAA":"Aviation Ordnanceman Airman Apprentice",
    "AC3":"Air Traffic Controller Petty Officer 3rd Class",
    "ACAR":"Air Control Man Airman Recruit",
    "HT3":"Hull Maintenance Technician Petty Officer 3rd Class",
    "RP":"Religious Program Specialist",
}

administrative = "CTM3, LNC, IS3, MCCS, PSSN, MA2, CS1, ISSN, ITSR, YN2, YNSR, JO3, CTR, DK3, ACAN, SKC, PNSN, PC1, SKSA, MC3, IC, LS, YN, EO3, AG, AC, CTT, PS, MC2, LS2, LS3, MA3, PSCM, OS1, DC2, NC1, ITCM, CTT3, PS3, AGAR, SKSN, SK2, IT1, CTR2, IC3, SK3, ICFN, IS1, CT, MA, EA, MC, SK, LN, AG3, IS2, PHAN, ITSN, IC1, SKSR, CTT2, PN2, OSSA, MA1, PCSN, AC1, IT2, ICC, YNSN, IC2, OS3, OSSN, AC2, SK1, CTTSN, ICFA, PN3, IT3, LISR, LISN, AC3, ACAR"

aircraft_upkeep = "AWSC, AWS2, AD1, ABF, AMEAN, AO2, AE1, ADAN, NA2, AME3, ATAN, AT3, AME2, AO1, ASAN, ABEAN, ADC, AMC, ADAA, AEC, AT1, AM2, AWF, ABE, AA, ABH1, AME, ABH2, AMAN, AMAA, AMAR, AE3, ABH, AW1, AW2, A03, AD, AT2, AB, AW3, AME1, AD3, AO, AT, AE, ABHC, AOC, ATC, AM1, AM3, ABHAA, AOAN, AD2, AEAN, AN, AR, ABHAN, ABH3, AE2, AECS, ABHAR, AW, AMAN, AK2, AOCM, AOC, ADCS, ADC, AA, ABHC, ADAR, AMEAA, AW2, AZ1, ASAR, AEAA, AG1, DCC, EMC, AR, ABH, AOCS, ABF2, AMAR, AT3, AE, PR, AK1, AW1, ATAA, AME, AZ, ABE, AO, AD, ABF, ASC, PR1, ATC, AME2, AZ2, AD3, AMEAN, AME3, AD1, ASAN, AT2, AMC, AM3, AE2, ABE1, ABE3, AOAN, AM2, ABH3, ABAN, AZAN, AD2, AM1, AO3, ABH1, ATAN, AS3, AS1, AEAN, ABE2, ABAA, AE3, PR3, PRAN, ABAR, AMEAR, AT1, ABF1, AZAA, AMEC, ADAA, AB1, AZ3, AMCS, AS2, AO2, ABH2, ABF3, AWAN, AEAR, ABFC, ADAN, AOAR, ABEC, AOAA" 

defense = "TM3, GM2, GMSR, GM3, TM2, GM, AM, TM1, GMSN, GMG, CTM, TM3, GMC"

ship_maintenance =  "QMSA, MMFN, RM2, AM, FC3,  PR2, EM1, QMSA, ETSN, HTC, HT1, FCC, BMC, DCCS, HTFR, SHCS, MMCS, MR3, EN2, ETC, MMFR, QMSN, ENFA, ENFN, QMCS, EM, FC, EN, MM, QM, DC, SH, MR, FR, FN, SHSR, FCSN, HT, ETCS, EACN, STG1, ET3, MR2, MR1, DCFN, DCFR, ET1, BMSN, DC3, DCFA, HM1, MMFN, STG, MM3, BM3, GSE, FA, FT, AV, ET, SHSN, MM1, EM3, MM2, MMFA, SH3, BMSA, EM2, SH2, EN3, SHSA, FC2, EMFA, BM2, EMFN, QM3, ET2, HTFA, EN1, MMC, HTFN, DC1, HT3"

personnel_maintenance = "HMC, HM2, RPC, HA, CS, CSCM, HM1, CS3, DT2, CSSA, DN, CSSN, CSSR, CS2, HM3, RP"

print("\n\n")
print("Adminstrative")
for item in administrative.split(", "):
    if item in aviation_ranks:
        print(aviation_ranks[item])
    elif item in non_aviation_ranks:
        print(non_aviation_ranks[item])

print("\n\n")
print("Aircraft Upkeep")
for item in aircraft_upkeep.split(", "):
    if item in aviation_ranks:
        print(aviation_ranks[item])
    elif item in non_aviation_ranks:
        print(non_aviation_ranks[item])

print("\n\n")
print("Defense")
for item in defense.split(", "):
    if item in aviation_ranks:
        print(aviation_ranks[item])
    elif item in non_aviation_ranks:
        print(non_aviation_ranks[item])

print("\n\n")
print("Ship Maintenance")
for item in ship_maintenance.split(", "):
    if item in aviation_ranks:
        print(aviation_ranks[item])
    elif item in non_aviation_ranks:
        print(non_aviation_ranks[item])

print("\n\n")
print("Personnel Maintenance")
for item in personnel_maintenance.split(", "):
    if item in aviation_ranks:
        print(aviation_ranks[item])
    elif item in non_aviation_ranks:
        print(non_aviation_ranks[item])

print("\n\n")
for item in aviation_ranks.keys():
    if aviation_ranks[item] == "***UNKNOWN***":
        print(item)
for item in non_aviation_ranks.keys():
    if non_aviation_ranks[item] == "***UNKNOWN***":
        print(item)